// Mocks generated by Mockito 5.4.4 from annotations
// in todo/test/test_utils/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dart_either/dart_either.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:todo/features/category/datasource/category_datasource.dart'
    as _i9;
import 'package:todo/features/category/models/category.dart' as _i7;
import 'package:todo/features/category/models/category_wrapper.dart' as _i2;
import 'package:todo/features/category/repository/category_repository.dart'
    as _i3;
import 'package:todo/features/custom_color/custom_color.dart' as _i8;
import 'package:todo/features/image/models/image.dart' as _i12;
import 'package:todo/features/image/models/image_wrapper.dart' as _i11;
import 'package:todo/features/image/repository/image_repository.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoryWrapper_0 extends _i1.SmartFake
    implements _i2.CategoryWrapper {
  _FakeCategoryWrapper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i3.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<String, List<_i2.CategoryWrapper>>> listCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #listCategories,
          [],
        ),
        returnValue:
            _i4.Future<_i5.Either<String, List<_i2.CategoryWrapper>>>.value(
                _i6.dummyValue<_i5.Either<String, List<_i2.CategoryWrapper>>>(
          this,
          Invocation.method(
            #listCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, List<_i2.CategoryWrapper>>>);

  @override
  _i4.Future<_i5.Either<String, _i2.CategoryWrapper>> getCategory(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategory,
          [id],
        ),
        returnValue: _i4.Future<_i5.Either<String, _i2.CategoryWrapper>>.value(
            _i6.dummyValue<_i5.Either<String, _i2.CategoryWrapper>>(
          this,
          Invocation.method(
            #getCategory,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, _i2.CategoryWrapper>>);

  @override
  _i4.Future<_i5.Either<String, dynamic>> addCategory(_i7.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i4.Future<_i5.Either<String, dynamic>>.value(
            _i6.dummyValue<_i5.Either<String, dynamic>>(
          this,
          Invocation.method(
            #addCategory,
            [category],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, dynamic>>);

  @override
  _i4.Future<_i5.Either<String, String>> deleteCategory(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i4.Future<_i5.Either<String, String>>.value(
            _i6.dummyValue<_i5.Either<String, String>>(
          this,
          Invocation.method(
            #deleteCategory,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, String>>);

  @override
  _i4.Future<_i5.Either<String, String>> updateCategory(
          _i2.CategoryWrapper? categoryWrapper) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [categoryWrapper],
        ),
        returnValue: _i4.Future<_i5.Either<String, String>>.value(
            _i6.dummyValue<_i5.Either<String, String>>(
          this,
          Invocation.method(
            #updateCategory,
            [categoryWrapper],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, String>>);
}

/// A class which mocks [CustomColorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomColorRepository extends _i1.Mock
    implements _i8.CustomColorRepository {
  MockCustomColorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<String, List<_i8.CustomColorWrapper>>>
      listCustomColors() => (super.noSuchMethod(
            Invocation.method(
              #listCustomColors,
              [],
            ),
            returnValue: _i4
                .Future<_i5.Either<String, List<_i8.CustomColorWrapper>>>.value(
                _i6.dummyValue<
                    _i5.Either<String, List<_i8.CustomColorWrapper>>>(
              this,
              Invocation.method(
                #listCustomColors,
                [],
              ),
            )),
          ) as _i4.Future<_i5.Either<String, List<_i8.CustomColorWrapper>>>);

  @override
  _i4.Future<_i5.Either<String, dynamic>> addCustomColor(int? color) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCustomColor,
          [color],
        ),
        returnValue: _i4.Future<_i5.Either<String, dynamic>>.value(
            _i6.dummyValue<_i5.Either<String, dynamic>>(
          this,
          Invocation.method(
            #addCustomColor,
            [color],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, dynamic>>);

  @override
  _i4.Future<_i5.Either<String, String>> deleteCustomColor(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomColor,
          [id],
        ),
        returnValue: _i4.Future<_i5.Either<String, String>>.value(
            _i6.dummyValue<_i5.Either<String, String>>(
          this,
          Invocation.method(
            #deleteCustomColor,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, String>>);
}

/// A class which mocks [CategoryDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryDatasource extends _i1.Mock
    implements _i9.CategoryDatasource {
  MockCategoryDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.CategoryWrapper>> listCategories() => (super.noSuchMethod(
        Invocation.method(
          #listCategories,
          [],
        ),
        returnValue: _i4.Future<List<_i2.CategoryWrapper>>.value(
            <_i2.CategoryWrapper>[]),
      ) as _i4.Future<List<_i2.CategoryWrapper>>);

  @override
  _i4.Future<_i2.CategoryWrapper> getCategory(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategory,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.CategoryWrapper>.value(_FakeCategoryWrapper_0(
          this,
          Invocation.method(
            #getCategory,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.CategoryWrapper>);

  @override
  _i4.Future<dynamic> addCategory(_i7.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<void> deleteCategory(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateCategory(_i2.CategoryWrapper? categoryWrapper) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [categoryWrapper],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ImageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageRepository extends _i1.Mock implements _i10.ImageRepository {
  MockImageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<String, List<_i11.ImageWrapper>>> listImages() =>
      (super.noSuchMethod(
        Invocation.method(
          #listImages,
          [],
        ),
        returnValue:
            _i4.Future<_i5.Either<String, List<_i11.ImageWrapper>>>.value(
                _i6.dummyValue<_i5.Either<String, List<_i11.ImageWrapper>>>(
          this,
          Invocation.method(
            #listImages,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, List<_i11.ImageWrapper>>>);

  @override
  _i4.Future<_i5.Either<String, _i12.Image>> getImage(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImage,
          [id],
        ),
        returnValue: _i4.Future<_i5.Either<String, _i12.Image>>.value(
            _i6.dummyValue<_i5.Either<String, _i12.Image>>(
          this,
          Invocation.method(
            #getImage,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, _i12.Image>>);

  @override
  _i4.Future<_i5.Either<String, String>> getTitle(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTitle,
          [id],
        ),
        returnValue: _i4.Future<_i5.Either<String, String>>.value(
            _i6.dummyValue<_i5.Either<String, String>>(
          this,
          Invocation.method(
            #getTitle,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, String>>);

  @override
  _i4.Future<_i5.Either<String, dynamic>> addImage(_i12.Image? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #addImage,
          [image],
        ),
        returnValue: _i4.Future<_i5.Either<String, dynamic>>.value(
            _i6.dummyValue<_i5.Either<String, dynamic>>(
          this,
          Invocation.method(
            #addImage,
            [image],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, dynamic>>);

  @override
  _i4.Future<_i5.Either<String, String>> deleteImage(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteImage,
          [id],
        ),
        returnValue: _i4.Future<_i5.Either<String, String>>.value(
            _i6.dummyValue<_i5.Either<String, String>>(
          this,
          Invocation.method(
            #deleteImage,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, String>>);

  @override
  _i4.Future<_i5.Either<String, String>> updateImage(
    dynamic id,
    _i12.Image? image,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateImage,
          [
            id,
            image,
          ],
        ),
        returnValue: _i4.Future<_i5.Either<String, String>>.value(
            _i6.dummyValue<_i5.Either<String, String>>(
          this,
          Invocation.method(
            #updateImage,
            [
              id,
              image,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Either<String, String>>);
}
